### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by ZhangYanTJU** [uqyge/oftrt#1]
Hi,
Thanks for your contribution!
I copied data/mnist from TensorRT-5.0.0.10/data/mnist.
But I encountered Floating point exception at this line:
```
mEngine = std::move(std::shared_ptr<nvinfer1::ICudaEngine>(builder->buildCudaEngine(*network), samplesCommon::InferDeleter()));
```
I found that it is caused by: ``builder->buildCudaEngine(*network)``.
But I cannot fixed this.

**Comment by uqyge** [comment]
It sounds like you have got a wrong model file. I have updated the demo and include the related caffe model.

**Comment by ZhangYanTJU** [comment]
Hi,
I found that your files in the dir "data" are exactly the same with mine.
Then the issue is still there.
PS: I am using cuda_9.0.176_384.81 cudnn-9.0-linux-x64-v7.3.1.20 and TensorRT-5.0.0.10.

**Comment by uqyge** [comment]
I have fixed the issue in the latest version. cudnn does some ops that could lead to cpu fpe. I have add an fpegard class to prevent the undesired fpe trapping from OpenFOAM.

> Hi,
> I found that your files in the dir "data" are exactly the same with mine.
> Then the issue is still there.
> PS: I am using cuda_9.0.176_384.81 cudnn-9.0-linux-x64-v7.3.1.20 and TensorRT-5.0.0.10.
